FROM node:18-alpine as build

WORKDIR /usr

ENV PATH /usr/node_modules/.bin:$PATH

COPY app/package.json ./

COPY app/package-lock.json ./

RUN npm ci

WORKDIR /usr/app

COPY app ./

RUN npm run build

FROM nginx:1.23.3-alpine

COPY --from=build /usr/app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d
